name: save-to-obsidian
display_name: "Save to Obsidian"
description: Saves markdown content to remote Obsidian vault via SSH
version: 1.1.0
triggers:
  - save to obsidian
  - send to obsidian
  - copy to obsidian
  - save this to obsidian
  - copy the output to obsidian
  - add this to my vault
  - put this in obsidian
